export type VocabularyWord = {
  id: string;
  word: string;
  meaning: string;
  meaningZh: string;
  soundParts: string[];
  example: string;
  pageIndex: number;
  icon: string;
  pronunciationHint?: string;
};

export const WORDS_PER_BOOK = 5;

export const WORD_SETS: Record<string, VocabularyWord[]> = {
  "dan-the-flying-man": [
    {
      id: "man",
      word: "man",
      meaning: "a grown-up male person",
      meaningZh: "男人",
      soundParts: ["m", "an"],
      example: "I am Dan, the flying man.",
      pageIndex: 1,
      icon: "🧑",
    },
    {
      id: "can",
      word: "can",
      meaning: "to be able to do something",
      meaningZh: "能够",
      soundParts: ["c", "an"],
      example: "Catch me if you can.",
      pageIndex: 1,
      icon: "💪",
    },
    {
      id: "over",
      word: "over",
      meaning: "above and across something",
      meaningZh: "越过；在上方",
      soundParts: ["o", "ver"],
      example: "Over a house and over a crane.",
      pageIndex: 2,
      icon: "🌈",
    },
    {
      id: "train",
      word: "train",
      meaning: "a long vehicle that runs on tracks",
      meaningZh: "火车",
      soundParts: ["tr", "ai", "n"],
      example: "Over a bridge and over a train.",
      pageIndex: 3,
      icon: "🚆",
    },
    {
      id: "trees",
      word: "trees",
      meaning: "tall plants with trunks and branches",
      meaningZh: "树（复数）",
      soundParts: ["tr", "ee", "s"],
      example: "Over flowers, over trees.",
      pageIndex: 4,
      icon: "🌳",
    },
  ],
  "mrs-wishy-washy": [
    {
      id: "cow",
      word: "cow",
      meaning: "a large farm animal that gives milk",
      meaningZh: "奶牛",
      soundParts: ["c", "ow"],
      example: "Oh, lovely mud, said the cow.",
      pageIndex: 0,
      icon: "🐄",
    },
    {
      id: "pig",
      word: "pig",
      meaning: "a pink farm animal",
      meaningZh: "猪",
      soundParts: ["p", "i", "g"],
      example: "Oh, lovely mud, said the pig.",
      pageIndex: 1,
      icon: "🐷",
    },
    {
      id: "duck",
      word: "duck",
      meaning: "a bird that swims and says quack",
      meaningZh: "鸭子",
      soundParts: ["d", "u", "ck"],
      example: "Oh, lovely mud, said the duck.",
      pageIndex: 2,
      icon: "🦆",
    },
    {
      id: "mud",
      word: "mud",
      meaning: "wet, soft earth",
      meaningZh: "泥巴",
      soundParts: ["m", "u", "d"],
      example: "Oh, lovely mud!",
      pageIndex: 0,
      icon: "🟤",
    },
    {
      id: "rolled",
      word: "rolled",
      meaning: "turned over and over",
      meaningZh: "打滚了",
      soundParts: ["r", "oll", "ed"],
      example: "He rolled in it.",
      pageIndex: 2,
      icon: "🌀",
    },
  ],
  "walking-through-jungle": [
    {
      id: "jungle",
      word: "jungle",
      meaning: "a hot, thick forest",
      meaningZh: "丛林",
      soundParts: ["jun", "gle"],
      example: "Walking through the jungle.",
      pageIndex: 0,
      icon: "🌴",
    },
    {
      id: "lion",
      word: "lion",
      meaning: "a big wild cat with a loud roar",
      meaningZh: "狮子",
      soundParts: ["li", "on"],
      example: "I think I see a lion.",
      pageIndex: 1,
      icon: "🦁",
    },
    {
      id: "whale",
      word: "whale",
      meaning: "a very large animal that lives in the sea",
      meaningZh: "鲸鱼",
      soundParts: ["wh", "ale"],
      example: "I think I see a whale.",
      pageIndex: 3,
      icon: "🐋",
    },
    {
      id: "ocean",
      word: "ocean",
      meaning: "a huge area of salt water",
      meaningZh: "海洋",
      soundParts: ["o", "cean"],
      example: "Floating on the ocean.",
      pageIndex: 2,
      icon: "🌊",
    },
    {
      id: "snake",
      word: "snake",
      meaning: "a long animal with no legs",
      meaningZh: "蛇",
      soundParts: ["sn", "ake"],
      example: "I think I see a snake.",
      pageIndex: 9,
      icon: "🐍",
    },
  ],
  "to-town": [
    {
      id: "town",
      word: "town",
      meaning: "a place where people live and work",
      meaningZh: "城镇",
      soundParts: ["t", "ow", "n"],
      example: "I will go to town.",
      pageIndex: 1,
      icon: "🏘️",
    },
    {
      id: "yellow",
      word: "yellow",
      meaning: "the colour of sunshine",
      meaningZh: "黄色",
      soundParts: ["yel", "low"],
      example: "My big yellow bulldozer.",
      pageIndex: 1,
      icon: "🟡",
    },
    {
      id: "red",
      word: "red",
      meaning: "the colour of a ripe tomato",
      meaningZh: "红色",
      soundParts: ["r", "e", "d"],
      example: "My big red fire-engine.",
      pageIndex: 2,
      icon: "🔴",
    },
    {
      id: "green",
      word: "green",
      meaning: "the colour of fresh leaves",
      meaningZh: "绿色",
      soundParts: ["gr", "ee", "n"],
      example: "My big green vintage car.",
      pageIndex: 3,
      icon: "🟢",
    },
    {
      id: "bike",
      word: "bike",
      meaning: "a vehicle with two wheels",
      meaningZh: "自行车；摩托车",
      soundParts: ["b", "ike"],
      example: "I will go to town on my motor bike.",
      pageIndex: 5,
      icon: "🏍️",
    },
  ],
  "the-hungry-giant": [
    {
      id: "giant",
      word: "giant",
      meaning: "a make-believe person who is very big",
      meaningZh: "巨人",
      soundParts: ["gi", "ant"],
      example: "The Hungry Giant.",
      pageIndex: 0,
      icon: "🧌",
    },
    {
      id: "bread",
      word: "bread",
      meaning: "food baked from flour and water",
      meaningZh: "面包",
      soundParts: ["br", "ea", "d"],
      example: "I want some bread!",
      pageIndex: 1,
      icon: "🍞",
    },
    {
      id: "butter",
      word: "butter",
      meaning: "a soft yellow food made from milk",
      meaningZh: "黄油",
      soundParts: ["but", "ter"],
      example: "I want some butter!",
      pageIndex: 2,
      icon: "🧈",
    },
    {
      id: "honey",
      word: "honey",
      meaning: "sweet food made by bees",
      meaningZh: "蜂蜜",
      soundParts: ["hon", "ey"],
      example: "I want some honey!",
      pageIndex: 3,
      icon: "🍯",
    },
    {
      id: "beehive",
      word: "beehive",
      meaning: "the home where bees live",
      meaningZh: "蜂巢",
      soundParts: ["bee", "hive"],
      example: "The people found a beehive.",
      pageIndex: 6,
      icon: "🐝",
    },
  ],
  "ants-in-a-hurry": [
    {
      id: "ants",
      word: "ants",
      meaning: "tiny insects that live together",
      meaningZh: "蚂蚁（复数）",
      soundParts: ["a", "n", "t", "s"],
      example: "The ants scurry, scurry, scurry.",
      pageIndex: 0,
      icon: "🐜",
    },
    {
      id: "hurry",
      word: "hurry",
      meaning: "to move or do something quickly",
      meaningZh: "赶快",
      soundParts: ["hur", "ry"],
      example: "Hurry, hurry, hurry!",
      pageIndex: 1,
      icon: "💨",
    },
    {
      id: "queen",
      word: "queen",
      meaning: "a woman ruler; the mother ant here",
      meaningZh: "女王；蚁后",
      soundParts: ["qu", "ee", "n"],
      example: "The Queen is hungry.",
      pageIndex: 1,
      icon: "👑",
    },
    {
      id: "jelly",
      word: "jelly",
      meaning: "a soft, wobbly sweet food",
      meaningZh: "果冻",
      soundParts: ["jel", "ly"],
      example: "The Queen wants her jelly.",
      pageIndex: 1,
      icon: "🍮",
    },
    {
      id: "hungry",
      word: "hungry",
      meaning: "wanting or needing food",
      meaningZh: "饥饿的",
      soundParts: ["hun", "gry"],
      example: "More and more baby ants are hungry!",
      pageIndex: 7,
      icon: "😋",
    },
  ],
  "dans-lost-hat": [
    {
      id: "lost",
      word: "lost",
      meaning: "not able to be found",
      meaningZh: "丢失的",
      soundParts: ["l", "o", "st"],
      example: "Dan has lost his flying hat.",
      pageIndex: 1,
      icon: "🔎",
    },
    {
      id: "hat",
      word: "hat",
      meaning: "something worn on the head",
      meaningZh: "帽子",
      soundParts: ["h", "at"],
      example: "He can't find his flying hat.",
      pageIndex: 2,
      icon: "🎩",
    },
    {
      id: "under",
      word: "under",
      meaning: "below something",
      meaningZh: "在……下面",
      soundParts: ["un", "der"],
      example: "He looks under the bed.",
      pageIndex: 1,
      icon: "⬇️",
    },
    {
      id: "cat",
      word: "cat",
      meaning: "a small furry pet that says meow",
      meaningZh: "猫",
      soundParts: ["c", "at"],
      example: "It's a large and fluffy tabby cat.",
      pageIndex: 5,
      icon: "🐈",
    },
    {
      id: "fish",
      word: "fish",
      meaning: "an animal that swims in water",
      meaningZh: "鱼",
      soundParts: ["f", "i", "sh"],
      example: "He puts some fish in a cat food dish.",
      pageIndex: 7,
      icon: "🐟",
    },
  ],
  "baby-sister-came-home": [
    {
      id: "baby",
      word: "baby",
      meaning: "a very young child",
      meaningZh: "婴儿",
      soundParts: ["ba", "by"],
      example: "My baby sister came home.",
      pageIndex: 0,
      icon: "👶",
    },
    {
      id: "sister",
      word: "sister",
      meaning: "a girl who has the same parent as you",
      meaningZh: "姐妹",
      soundParts: ["sis", "ter"],
      example: "My baby sister cried.",
      pageIndex: 1,
      icon: "👧",
    },
    {
      id: "cried",
      word: "cried",
      meaning: "made tears and a sad sound",
      meaningZh: "哭了",
      soundParts: ["cr", "ied"],
      example: "My baby sister cried.",
      pageIndex: 1,
      icon: "😢",
    },
    {
      id: "father",
      word: "father",
      meaning: "a male parent",
      meaningZh: "父亲",
      soundParts: ["fa", "ther"],
      example: "Father carried her.",
      pageIndex: 2,
      icon: "👨",
    },
    {
      id: "brother",
      word: "brother",
      meaning: "a boy who has the same parent as you",
      meaningZh: "兄弟",
      soundParts: ["bro", "ther"],
      example: "Your brother didn't cry when he came home.",
      pageIndex: 5,
      icon: "👦",
    },
  ],
  "mid-autumn-festival": [
    {
      id: "lantern",
      word: "lantern",
      meaning: "a light inside a case that you can carry",
      meaningZh: "灯笼",
      soundParts: ["lan", "tern"],
      example: "I want a tiger lantern.",
      pageIndex: 1,
      icon: "🏮",
    },
    {
      id: "tiger",
      word: "tiger",
      meaning: "a large striped wild cat",
      meaningZh: "老虎",
      soundParts: ["ti", "ger"],
      example: "May I have that tiger lantern?",
      pageIndex: 1,
      icon: "🐯",
    },
    {
      id: "rabbit",
      word: "rabbit",
      meaning: "a small animal with long ears",
      meaningZh: "兔子",
      soundParts: ["rab", "bit"],
      example: "Lee Ling held her rabbit lantern.",
      pageIndex: 2,
      icon: "🐇",
    },
    {
      id: "mooncake",
      word: "mooncake",
      meaning: "a round cake eaten at Mid-Autumn Festival",
      meaningZh: "月饼",
      soundParts: ["moon", "cake"],
      example: "We stopped at the mooncake stall.",
      pageIndex: 3,
      icon: "🥮",
    },
    {
      id: "behind",
      word: "behind",
      meaning: "at the back of something",
      meaningZh: "在……后面",
      soundParts: ["be", "hind"],
      example: "Behind the stall was Lee Ling.",
      pageIndex: 7,
      icon: "↩️",
    },
  ],
  "first-day-hari-raya": [
    {
      id: "baju",
      word: "baju",
      meaning: "a Malay word for clothing",
      meaningZh: "马来语：衣服",
      soundParts: ["ba", "ju"],
      example: "Look at my baju kurung!",
      pageIndex: 3,
      icon: "👚",
      pronunciationHint: "BAH-joo",
    },
    {
      id: "kurung",
      word: "kurung",
      meaning: "part of a traditional Malay outfit",
      meaningZh: "马来传统服装",
      soundParts: ["ku", "rung"],
      example: "My baju kurung is green.",
      pageIndex: 3,
      icon: "🧵",
      pronunciationHint: "koo-ROONG",
    },
    {
      id: "green",
      word: "green",
      meaning: "the colour of fresh leaves",
      meaningZh: "绿色",
      soundParts: ["gr", "ee", "n"],
      example: "My baju kurung is green.",
      pageIndex: 3,
      icon: "🟢",
    },
    {
      id: "visit",
      word: "visit",
      meaning: "to go and spend time with someone",
      meaningZh: "拜访",
      soundParts: ["vis", "it"],
      example: "We are going to visit Grandpa and Grandma.",
      pageIndex: 2,
      icon: "🚪",
    },
    {
      id: "family",
      word: "family",
      meaning: "people who are related and care for one another",
      meaningZh: "家人；家庭",
      soundParts: ["fam", "i", "ly"],
      example: "All the family members are at the house.",
      pageIndex: 6,
      icon: "👨‍👩‍👧‍👦",
    },
  ],
  "lazy-duck": [
    {
      id: "waddled",
      word: "waddled",
      meaning: "walked with short steps from side to side",
      meaningZh: "摇摇摆摆地走",
      soundParts: ["w", "add", "led"],
      example: "Lazy Duck waddled around the farmyard.",
      pageIndex: 1,
      icon: "🦆",
    },
    {
      id: "farmyard",
      word: "farmyard",
      meaning: "the open area beside farm buildings",
      meaningZh: "农场院子",
      soundParts: ["farm", "yard"],
      example: "Lazy Duck waddled around the farmyard.",
      pageIndex: 1,
      icon: "🚜",
    },
    {
      id: "prowled",
      word: "prowled",
      meaning: "moved around quietly while looking for something",
      meaningZh: "悄悄地四处走动",
      soundParts: ["pr", "owl", "ed"],
      example: "She prowled up and down looking for mice.",
      pageIndex: 2,
      icon: "🐈",
    },
    {
      id: "scratched",
      word: "scratched",
      meaning: "scraped a surface with claws or something sharp",
      meaningZh: "抓挖了",
      soundParts: ["scr", "atch", "ed"],
      example: "They scratched and scraped.",
      pageIndex: 3,
      icon: "🐔",
    },
    {
      id: "busiest",
      word: "busiest",
      meaning: "doing more work than everyone else",
      meaningZh: "最忙碌的",
      soundParts: ["bus", "i", "est"],
      example: "I'm the busiest duck you've seen.",
      pageIndex: 10,
      icon: "🧹",
    },
  ],
  "mr-gumpys-outing": [
    {
      id: "river",
      word: "river",
      meaning: "a large natural stream of water",
      meaningZh: "河流",
      soundParts: ["riv", "er"],
      example: "His house was by a river.",
      pageIndex: 2,
      icon: "🌊",
    },
    {
      id: "squabble",
      word: "squabble",
      meaning: "to argue noisily about a small thing",
      meaningZh: "争吵",
      soundParts: ["squ", "ab", "ble"],
      example: "If you don't squabble.",
      pageIndex: 3,
      icon: "🗣️",
    },
    {
      id: "bleating",
      word: "bleating",
      meaning: "making the sound of a sheep or goat",
      meaningZh: "咩咩叫",
      soundParts: ["bl", "eat", "ing"],
      example: "Don't keep bleating.",
      pageIndex: 8,
      icon: "🐑",
    },
    {
      id: "trample",
      word: "trample",
      meaning: "to step heavily on things",
      meaningZh: "踩踏",
      soundParts: ["tr", "am", "ple"],
      example: "If you don't trample about.",
      pageIndex: 10,
      icon: "🐂",
    },
    {
      id: "tipped",
      word: "tipped",
      meaning: "leaned too far to one side",
      meaningZh: "倾斜了",
      soundParts: ["t", "ipp", "ed"],
      example: "The boat tipped.",
      pageIndex: 12,
      icon: "🚣",
    },
  ],
  "a-day-in-the-kitchen-with-grandma": [
    {
      id: "dough",
      word: "dough",
      meaning: "a soft mixture used to make bread or noodles",
      meaningZh: "面团",
      soundParts: ["d", "ough"],
      example: "Grandma mixes the flour, water and salt to make dough.",
      pageIndex: 1,
      icon: "🫓",
    },
    {
      id: "dumplings",
      word: "dumplings",
      meaning: "small pieces of filled or shaped dough or rice food",
      meaningZh: "粽子；饺子类食物",
      soundParts: ["dump", "lings"],
      example: "Let's make rice dumplings!",
      pageIndex: 3,
      icon: "🥟",
    },
    {
      id: "bamboo",
      word: "bamboo",
      meaning: "a tall plant with hard hollow stems",
      meaningZh: "竹子",
      soundParts: ["bam", "boo"],
      example: "Some bamboo leaves on the table.",
      pageIndex: 3,
      icon: "🎋",
    },
    {
      id: "soaked",
      word: "soaked",
      meaning: "left something in liquid until it became very wet",
      meaningZh: "浸泡了",
      soundParts: ["s", "oak", "ed"],
      example: "I soaked some rice in the blue water.",
      pageIndex: 4,
      icon: "💧",
    },
    {
      id: "noodles",
      word: "noodles",
      meaning: "long thin strips of food made from dough",
      meaningZh: "面条",
      soundParts: ["noo", "dles"],
      example: "We start to make noodles.",
      pageIndex: 8,
      icon: "🍜",
    },
  ],
  "life-in-a-shell": [
    {
      id: "protect",
      word: "protect",
      meaning: "to keep someone or something safe",
      meaningZh: "保护",
      soundParts: ["pro", "tect"],
      example: "Their shells protect them.",
      pageIndex: 2,
      icon: "🛡️",
    },
    {
      id: "danger",
      word: "danger",
      meaning: "the chance that something harmful may happen",
      meaningZh: "危险",
      soundParts: ["dan", "ger"],
      example: "When there is danger, a snail pulls its whole body inside its shell.",
      pageIndex: 4,
      icon: "⚠️",
    },
    {
      id: "exoskeleton",
      word: "exoskeleton",
      meaning: "a hard skeleton on the outside of a creature",
      meaningZh: "外骨骼",
      soundParts: ["exo", "skeleton"],
      example: "The shell of a crab or a lobster is called an exoskeleton.",
      pageIndex: 8,
      icon: "🦀",
    },
    {
      id: "hermit",
      word: "hermit",
      meaning: "part of the name for a crab that lives in an empty shell",
      meaningZh: "寄居的",
      soundParts: ["her", "mit"],
      example: "A hermit crab does not have a shell on its body.",
      pageIndex: 10,
      icon: "🐚",
    },
    {
      id: "tide",
      word: "tide",
      meaning: "the regular rise and fall of the sea",
      meaningZh: "潮汐",
      soundParts: ["t", "ide"],
      example: "This happens when the tide comes in.",
      pageIndex: 14,
      icon: "🌊",
    },
  ],
  "the-growl": [
    {
      id: "rumble",
      word: "rumble",
      meaning: "a low, deep continuous sound",
      meaningZh: "低沉的隆隆声",
      soundParts: ["rum", "ble"],
      example: "I heard a little rumble.",
      pageIndex: 1,
      icon: "🌩️",
    },
    {
      id: "classroom",
      word: "classroom",
      meaning: "a room where a class learns",
      meaningZh: "教室",
      soundParts: ["class", "room"],
      example: "I looked around the classroom.",
      pageIndex: 1,
      icon: "🏫",
    },
    {
      id: "grizzly",
      word: "grizzly",
      meaning: "a large brown bear",
      meaningZh: "灰熊",
      soundParts: ["grizz", "ly"],
      example: "Was it coming from a grizzly bear?",
      pageIndex: 4,
      icon: "🐻",
    },
    {
      id: "hungry",
      word: "hungry",
      meaning: "needing or wanting food",
      meaningZh: "饥饿的",
      soundParts: ["hun", "gry"],
      example: "I am so hungry I could eat a horse!",
      pageIndex: 5,
      icon: "🍽️",
    },
    {
      id: "lunch",
      word: "lunch",
      meaning: "the meal eaten around the middle of the day",
      meaningZh: "午餐",
      soundParts: ["l", "unch"],
      example: "Please go and eat your lunch.",
      pageIndex: 7,
      icon: "🍱",
    },
  ],
  "magnetic-max": [
    {
      id: "keys",
      word: "keys",
      meaning: "small metal tools used to open locks",
      meaningZh: "钥匙",
      soundParts: ["k", "ey", "s"],
      example: "The keys went flying into the tree.",
      pageIndex: 4,
      icon: "🔑",
    },
    {
      id: "bolts",
      word: "bolts",
      meaning: "metal fasteners used to hold parts together",
      meaningZh: "螺栓",
      soundParts: ["b", "olt", "s"],
      example: "The iron bolts on his skateboard came out.",
      pageIndex: 6,
      icon: "🔩",
    },
    {
      id: "branches",
      word: "branches",
      meaning: "the parts of a tree that grow out from its trunk",
      meaningZh: "树枝",
      soundParts: ["branch", "es"],
      example: "Hidden by the branches",
      pageIndex: 7,
      icon: "🌳",
    },
    {
      id: "enormous",
      word: "enormous",
      meaning: "very, very large",
      meaningZh: "巨大的",
      soundParts: ["e", "nor", "mous"],
      example: "Max, holding an enormous magnet.",
      pageIndex: 8,
      icon: "🧲",
    },
    {
      id: "magnetic",
      word: "magnetic",
      meaning: "able to attract iron or steel",
      meaningZh: "有磁性的",
      soundParts: ["mag", "net", "ic"],
      example: "Just call me Magnetic Max.",
      pageIndex: 8,
      icon: "🧲",
    },
  ],
  "the-feast": [
    {
      id: "feast",
      word: "feast",
      meaning: "a large special meal",
      meaningZh: "盛宴",
      soundParts: ["f", "east"],
      example: "Come to my dinosaur feast!",
      pageIndex: 2,
      icon: "🍽️",
    },
    {
      id: "delicious",
      word: "delicious",
      meaning: "tasting or smelling very good",
      meaningZh: "美味的",
      soundParts: ["de", "li", "cious"],
      example: "Tasty cakes and delicious ham!",
      pageIndex: 2,
      icon: "😋",
    },
    {
      id: "furious",
      word: "furious",
      meaning: "extremely angry",
      meaningZh: "非常愤怒的",
      soundParts: ["fu", "ri", "ous"],
      example: "Dragon was furious.",
      pageIndex: 8,
      icon: "🔥",
    },
    {
      id: "invitations",
      word: "invitations",
      meaning: "messages asking people to come to an event",
      meaningZh: "邀请函",
      soundParts: ["in", "vi", "ta", "tions"],
      example: "I will make invitations.",
      pageIndex: 12,
      icon: "💌",
    },
    {
      id: "midnight",
      word: "midnight",
      meaning: "twelve o'clock at night",
      meaningZh: "午夜",
      soundParts: ["mid", "night"],
      example: "Saturday night at midnight.",
      pageIndex: 12,
      icon: "🌙",
    },
  ],
  "willy-and-hugh": [
    {
      id: "lonely",
      word: "lonely",
      meaning: "sad because you do not have anyone with you",
      meaningZh: "孤独的",
      soundParts: ["lone", "ly"],
      example: "Willy was lonely.",
      pageIndex: 1,
      icon: "😔",
    },
    {
      id: "useless",
      word: "useless",
      meaning: "not able to help or do what is needed",
      meaningZh: "没有用的",
      soundParts: ["use", "less"],
      example: "They all said he was useless.",
      pageIndex: 3,
      icon: "🤷",
    },
    {
      id: "amazed",
      word: "amazed",
      meaning: "very surprised",
      meaningZh: "惊讶的",
      soundParts: ["a", "maz", "ed"],
      example: "Willy was amazed.",
      pageIndex: 5,
      icon: "😲",
    },
    {
      id: "bench",
      word: "bench",
      meaning: "a long seat for several people",
      meaningZh: "长椅",
      soundParts: ["b", "ench"],
      example: "They sat down on a bench.",
      pageIndex: 6,
      icon: "🪑",
    },
    {
      id: "terrifying",
      word: "terrifying",
      meaning: "making someone feel very afraid",
      meaningZh: "令人恐惧的",
      soundParts: ["ter", "ri", "fy", "ing"],
      example: "He'd seen a terrifying creature!",
      pageIndex: 10,
      icon: "😱",
    },
  ],
  "the-gruffalo": [
    {
      id: "stroll",
      word: "stroll",
      meaning: "to walk in a slow, relaxed way",
      meaningZh: "悠闲地走",
      soundParts: ["str", "oll"],
      example: "A mouse took a stroll through the deep dark wood.",
      pageIndex: 1,
      icon: "🚶",
    },
    {
      id: "tusks",
      word: "tusks",
      meaning: "long pointed teeth that grow outside the mouth",
      meaningZh: "长而尖的牙",
      soundParts: ["t", "u", "sks"],
      example: "He has terrible tusks, and terrible claws",
      pageIndex: 2,
      icon: "🐘",
    },
    {
      id: "claws",
      word: "claws",
      meaning: "sharp curved nails on an animal",
      meaningZh: "动物的利爪",
      soundParts: ["cl", "aw", "s"],
      example: "He has terrible tusks, and terrible claws",
      pageIndex: 2,
      icon: "🐾",
    },
    {
      id: "prickles",
      word: "prickles",
      meaning: "small sharp points on a plant or animal",
      meaningZh: "细小尖刺",
      soundParts: ["prick", "les"],
      example: "He has purple prickles all over his back.",
      pageIndex: 6,
      icon: "🦔",
    },
    {
      id: "crumble",
      word: "crumble",
      meaning: "a baked dessert with a crumbly topping",
      meaningZh: "酥粒烤甜点",
      soundParts: ["crum", "ble"],
      example: "My favourite food is — gruffalo crumble!",
      pageIndex: 11,
      icon: "🥧",
    },
  ],
  "predators-and-prey": [
    {
      id: "predator",
      word: "predator",
      meaning: "an animal that hunts other animals for food",
      meaningZh: "捕食者",
      soundParts: ["pred", "a", "tor"],
      example: "The cheetah is the predator.",
      pageIndex: 2,
      icon: "🐆",
    },
    {
      id: "prey",
      word: "prey",
      meaning: "an animal hunted by another animal",
      meaningZh: "猎物",
      soundParts: ["pr", "ey"],
      example: "The gazelle is the prey.",
      pageIndex: 2,
      icon: "🦌",
    },
    {
      id: "dodges",
      word: "dodges",
      meaning: "moves quickly out of the way",
      meaningZh: "迅速闪避",
      soundParts: ["dodg", "es"],
      example: "It runs and dodges until the cheetah is out of energy.",
      pageIndex: 2,
      icon: "💨",
    },
    {
      id: "burrows",
      word: "burrows",
      meaning: "animal homes or tunnels underground",
      meaningZh: "洞穴；地洞",
      soundParts: ["bur", "rows"],
      example: "All the prairie dogs race into their burrows.",
      pageIndex: 4,
      icon: "🕳️",
    },
    {
      id: "venom",
      word: "venom",
      meaning: "a poisonous substance made by some animals",
      meaningZh: "毒液",
      soundParts: ["ven", "om"],
      example: "The cobra has venom that can stop the mongoose in its tracks.",
      pageIndex: 7,
      icon: "🐍",
    },
  ],
  "the-stars-of-chek-jawa": [
    {
      id: "wetlands",
      word: "wetlands",
      meaning: "land that is covered or soaked with water",
      meaningZh: "湿地",
      soundParts: ["wet", "lands"],
      example: "The Chek Jawa wetlands in Pulau Ubin were a secret for many years.",
      pageIndex: 1,
      icon: "🌿",
    },
    {
      id: "marine",
      word: "marine",
      meaning: "connected with the sea",
      meaningZh: "海洋的",
      soundParts: ["ma", "rine"],
      example: "One of the most interesting kinds of marine life in Chek Jawa is the sea star.",
      pageIndex: 2,
      icon: "🌊",
    },
    {
      id: "echinoderms",
      word: "echinoderms",
      meaning: "sea animals with spiny skin, such as sea stars",
      meaningZh: "棘皮动物",
      soundParts: ["e", "chi", "no", "derms"],
      example: "They are known as echinoderms, which means spiny skin.",
      pageIndex: 2,
      icon: "⭐",
      pronunciationHint: "ee-KY-no-derms",
    },
    {
      id: "detach",
      word: "detach",
      meaning: "to separate or break away",
      meaningZh: "脱落；分离",
      soundParts: ["de", "tach"],
      example: "If a sea star is in danger, it may detach its arm to escape.",
      pageIndex: 3,
      icon: "↗️",
    },
    {
      id: "predators",
      word: "predators",
      meaning: "animals that hunt other animals",
      meaningZh: "捕食者（复数）",
      soundParts: ["pred", "a", "tors"],
      example: "make it difficult for fish and other predators to bite it.",
      pageIndex: 4,
      icon: "🦈",
    },
  ],
  "dinosaur-school": [
    {
      id: "teasing",
      word: "teasing",
      meaning: "making fun of someone in an unkind way",
      meaningZh: "取笑；戏弄",
      soundParts: ["teas", "ing"],
      example: "They've been teasing me.",
      pageIndex: 1,
      icon: "😢",
    },
    {
      id: "playschool",
      word: "playschool",
      meaning: "a school for very young children",
      meaningZh: "幼儿学校",
      soundParts: ["play", "school"],
      example: "A variety of little dinosaurs went to the playschool.",
      pageIndex: 2,
      icon: "🏫",
    },
    {
      id: "brains",
      word: "brains",
      meaning: "the organs inside the head used for thinking",
      meaningZh: "大脑（复数）",
      soundParts: ["br", "ai", "ns"],
      example: "We have two brains.",
      pageIndex: 4,
      icon: "🧠",
    },
    {
      id: "expelled",
      word: "expelled",
      meaning: "officially made to leave a school",
      meaningZh: "被学校开除",
      soundParts: ["ex", "pelled"],
      example: "Not long after this, Basil was expelled.",
      pageIndex: 9,
      icon: "🚪",
    },
    {
      id: "terrifying",
      word: "terrifying",
      meaning: "making someone feel very afraid",
      meaningZh: "令人恐惧的",
      soundParts: ["ter", "ri", "fy", "ing"],
      example: "Basil looked up to see a terrifying sight.",
      pageIndex: 12,
      icon: "😱",
    },
  ],
  "danny-dinosaur-goes-to-camp": [
    {
      id: "camp",
      word: "camp",
      meaning: "a place where children stay and enjoy activities",
      meaningZh: "夏令营；营地",
      soundParts: ["c", "amp"],
      example: "Danny went to camp for the summer.",
      pageIndex: 2,
      icon: "🏕️",
    },
    {
      id: "vacation",
      word: "vacation",
      meaning: "time away from work or school for rest and fun",
      meaningZh: "假期",
      soundParts: ["va", "ca", "tion"],
      example: "Thanks. I needed a vacation.",
      pageIndex: 3,
      icon: "☀️",
    },
    {
      id: "race",
      word: "race",
      meaning: "a contest to see who can move fastest",
      meaningZh: "赛跑；比赛",
      soundParts: ["r", "ace"],
      example: "Let's start with a race.",
      pageIndex: 4,
      icon: "🏁",
    },
    {
      id: "touchdown",
      word: "touchdown",
      meaning: "a scoring play in American football",
      meaningZh: "达阵得分",
      soundParts: ["touch", "down"],
      example: "Touchdown!",
      pageIndex: 5,
      icon: "🏈",
    },
    {
      id: "marshmallows",
      word: "marshmallows",
      meaning: "soft, sweet treats often toasted over a fire",
      meaningZh: "棉花糖（复数）",
      soundParts: ["marsh", "mal", "lows"],
      example: "Lana gave out toasted marshmallows.",
      pageIndex: 12,
      icon: "🔥",
    },
  ],
  "danny-dinosaur-school-days": [
    {
      id: "museum",
      word: "museum",
      meaning: "a place where interesting objects are kept and shown",
      meaningZh: "博物馆",
      soundParts: ["mu", "se", "um"],
      example: "he left the museum to see what school was all about.",
      pageIndex: 2,
      icon: "🏛️",
    },
    {
      id: "measurements",
      word: "measurements",
      meaning: "numbers that show the size or amount of something",
      meaningZh: "测量结果；尺寸",
      soundParts: ["mea", "sure", "ments"],
      example: "Danny's class learned about math and measurements.",
      pageIndex: 7,
      icon: "📏",
    },
    {
      id: "stomping",
      word: "stomping",
      meaning: "walking with heavy, noisy steps",
      meaningZh: "重重地踏步",
      soundParts: ["stomp", "ing"],
      example: "Danny's class even tried stomping like dinosaurs!",
      pageIndex: 10,
      icon: "🦖",
    },
    {
      id: "cafeteria",
      word: "cafeteria",
      meaning: "a place at school where people buy and eat food",
      meaningZh: "学校餐厅",
      soundParts: ["caf", "e", "te", "ri", "a"],
      example: "The cafeteria had sloppy joes.",
      pageIndex: 12,
      icon: "🍽️",
    },
    {
      id: "cheered",
      word: "cheered",
      meaning: "shouted happily to show support or excitement",
      meaningZh: "欢呼",
      soundParts: ["cheer", "ed"],
      example: "Everyone cheered.",
      pageIndex: 15,
      icon: "🎉",
    },
  ],
  "santas-moose": [
    {
      id: "reindeer",
      word: "reindeer",
      meaning: "a deer that lives in cold northern places",
      meaningZh: "驯鹿",
      soundParts: ["rein", "deer"],
      example: "said eight little reindeer.",
      pageIndex: 4,
      icon: "🦌",
    },
    {
      id: "sleigh",
      word: "sleigh",
      meaning: "a vehicle that slides over snow",
      meaningZh: "雪橇",
      soundParts: ["sl", "eigh"],
      example: "May I please help pull your sleigh?",
      pageIndex: 5,
      icon: "🛷",
    },
    {
      id: "practice",
      word: "practice",
      meaning: "doing something again to improve",
      meaningZh: "练习",
      soundParts: ["prac", "tice"],
      example: "All it takes is practice.",
      pageIndex: 9,
      icon: "🎯",
    },
    {
      id: "stockings",
      word: "stockings",
      meaning: "long socks used for Christmas gifts",
      meaningZh: "圣诞袜（复数）",
      soundParts: ["stock", "ings"],
      example: "and candy in the stockings.",
      pageIndex: 12,
      icon: "🧦",
    },
    {
      id: "delivered",
      word: "delivered",
      meaning: "taken to the correct person or place",
      meaningZh: "送达了",
      soundParts: ["de", "liv", "ered"],
      example: "All the toys were delivered.",
      pageIndex: 14,
      icon: "🎁",
    },
  ],
  "horse-in-harrys-room": [
    {
      id: "horse",
      word: "horse",
      meaning: "a large animal people can ride",
      meaningZh: "马",
      soundParts: ["h", "orse"],
      example: "Oh, it's great to have a horse,",
      pageIndex: 4,
      icon: "🐴",
    },
    {
      id: "country",
      word: "country",
      meaning: "land outside towns and cities",
      meaningZh: "乡村",
      soundParts: ["coun", "try"],
      example: "Let's take Harry to the country,",
      pageIndex: 7,
      icon: "🌳",
    },
    {
      id: "circle",
      word: "circle",
      meaning: "a round shape with no corners",
      meaningZh: "圆圈",
      soundParts: ["cir", "cle"],
      example: "I can ride him in a circle",
      pageIndex: 10,
      icon: "⭕",
    },
    {
      id: "ceiling",
      word: "ceiling",
      meaning: "the inside surface at the top of a room",
      meaningZh: "天花板",
      soundParts: ["ceil", "ing"],
      example: "without hitting my head on the ceiling.",
      pageIndex: 10,
      icon: "🏠",
    },
    {
      id: "nibbling",
      word: "nibbling",
      meaning: "taking small bites of food",
      meaningZh: "小口地啃",
      soundParts: ["nib", "bling"],
      example: "Harry saw horses nibbling.",
      pageIndex: 13,
      icon: "🌿",
    },
  ],
  "danny-dinosaur-too-tall": [
    {
      id: "different",
      word: "different",
      meaning: "not the same as something else",
      meaningZh: "不同的",
      soundParts: ["dif", "fer", "ent"],
      example: "It's not easy being different,",
      pageIndex: 2,
      icon: "🌈",
    },
    {
      id: "sunshine",
      word: "sunshine",
      meaning: "light and warmth from the sun",
      meaningZh: "阳光",
      soundParts: ["sun", "shine"],
      example: "Being tall isn't all sunshine and rainbows,",
      pageIndex: 7,
      icon: "☀️",
    },
    {
      id: "giraffes",
      word: "giraffes",
      meaning: "very tall animals with long necks",
      meaningZh: "长颈鹿（复数）",
      soundParts: ["gi", "raffes"],
      example: "Giraffes are tall like you,",
      pageIndex: 9,
      icon: "🦒",
    },
    {
      id: "crane",
      word: "crane",
      meaning: "a tall machine used to lift heavy things",
      meaningZh: "起重机",
      soundParts: ["cr", "ane"],
      example: "and the crane swayed.",
      pageIndex: 13,
      icon: "🏗️",
    },
    {
      id: "safely",
      word: "safely",
      meaning: "without being hurt or damaged",
      meaningZh: "安全地",
      soundParts: ["safe", "ly"],
      example: "and the dinosaur took him safely to the ground.",
      pageIndex: 15,
      icon: "🛟",
    },
  ],
  "danny-dinosaur-sand-castle-contest": [
    {
      id: "beach",
      word: "beach",
      meaning: "a sandy place beside the sea",
      meaningZh: "海滩",
      soundParts: ["b", "each"],
      example: "We're going to the beach tomorrow,",
      pageIndex: 2,
      icon: "🏖️",
    },
    {
      id: "contest",
      word: "contest",
      meaning: "an event where people try to win",
      meaningZh: "比赛",
      soundParts: ["con", "test"],
      example: "It's the sand castle contest.",
      pageIndex: 5,
      icon: "🏆",
    },
    {
      id: "helpful",
      word: "helpful",
      meaning: "giving help to another person",
      meaningZh: "乐于助人的",
      soundParts: ["help", "ful"],
      example: "but he was a little too helpful.",
      pageIndex: 6,
      icon: "🤝",
    },
    {
      id: "tide",
      word: "tide",
      meaning: "the regular rise and fall of sea water",
      meaningZh: "潮水",
      soundParts: ["t", "ide"],
      example: "The tide was coming in.",
      pageIndex: 11,
      icon: "🌊",
    },
    {
      id: "celebrated",
      word: "celebrated",
      meaning: "did something enjoyable for a special event",
      meaningZh: "庆祝了",
      soundParts: ["cel", "e", "brat", "ed"],
      example: "everyone celebrated with Popsicles.",
      pageIndex: 16,
      icon: "🎊",
    },
  ],
  "danny-dinosaur-new-puppy": [
    {
      id: "puppy",
      word: "puppy",
      meaning: "a young dog",
      meaningZh: "小狗",
      soundParts: ["pup", "py"],
      example: "I was talking to my new puppy.",
      pageIndex: 3,
      icon: "🐶",
    },
    {
      id: "fetch",
      word: "fetch",
      meaning: "to go and bring something back",
      meaningZh: "取回来",
      soundParts: ["f", "etch"],
      example: "Danny threw a stick. Fetch!",
      pageIndex: 4,
      icon: "🦴",
    },
    {
      id: "pirates",
      word: "pirates",
      meaning: "people who sail and steal from ships",
      meaningZh: "海盗（复数）",
      soundParts: ["pi", "rates"],
      example: "The friends played at being pirates.",
      pageIndex: 9,
      icon: "🏴‍☠️",
    },
    {
      id: "sleepover",
      word: "sleepover",
      meaning: "a night spent sleeping at a friend's home",
      meaningZh: "留宿聚会",
      soundParts: ["sleep", "o", "ver"],
      example: "Time for a sleepover!",
      pageIndex: 14,
      icon: "🌙",
    },
    {
      id: "snuggled",
      word: "snuggled",
      meaning: "settled closely and comfortably",
      meaningZh: "依偎着",
      soundParts: ["snug", "gled"],
      example: "Then they snuggled up to sleep.",
      pageIndex: 15,
      icon: "🛏️",
    },
  ],
  "sammy-the-seal": [
    {
      id: "zoo",
      word: "zoo",
      meaning: "a place where people can see animals",
      meaningZh: "动物园",
      soundParts: ["z", "oo"],
      example: "It was feeding time at the zoo.",
      pageIndex: 2,
      icon: "🦁",
    },
    {
      id: "basket",
      word: "basket",
      meaning: "a container woven from thin strips",
      meaningZh: "篮子",
      soundParts: ["bas", "ket"],
      example: "Soon the basket was empty.",
      pageIndex: 6,
      icon: "🧺",
    },
    {
      id: "stranger",
      word: "stranger",
      meaning: "a person you do not know",
      meaningZh: "陌生人",
      soundParts: ["stran", "ger"],
      example: "I am a stranger here myself,",
      pageIndex: 12,
      icon: "👤",
    },
    {
      id: "flippers",
      word: "flippers",
      meaning: "wide flat limbs used by sea animals for swimming",
      meaningZh: "鳍状肢（复数）",
      soundParts: ["flip", "pers"],
      example: "Sammy tried to catch the ball with his flippers.",
      pageIndex: 28,
      icon: "🦭",
    },
    {
      id: "belong",
      word: "belong",
      meaning: "to be in the right place or group",
      meaningZh: "属于；适合待在",
      soundParts: ["be", "long"],
      example: "School is fun, but I belong in the zoo.",
      pageIndex: 29,
      icon: "🏡",
    },
  ],
  "danny-dinosaur-mind-manners": [
    {
      id: "royalty",
      word: "royalty",
      meaning: "kings, queens, and their families",
      meaningZh: "王室成员",
      soundParts: ["roy", "al", "ty"],
      example: "Wow, I've never met royalty,",
      pageIndex: 3,
      icon: "👑",
    },
    {
      id: "behavior",
      word: "behavior",
      meaning: "the way someone acts",
      meaningZh: "行为举止",
      soundParts: ["be", "hav", "ior"],
      example: "we have to be on our best behavior.",
      pageIndex: 4,
      icon: "🙂",
    },
    {
      id: "manners",
      word: "manners",
      meaning: "polite ways of behaving",
      meaningZh: "礼貌；礼仪",
      soundParts: ["man", "ners"],
      example: "Maybe our manners need work.",
      pageIndex: 4,
      icon: "🙏",
    },
    {
      id: "compliment",
      word: "compliment",
      meaning: "to say something nice about someone or something",
      meaningZh: "称赞",
      soundParts: ["com", "pli", "ment"],
      example: "It's polite to compliment the cook after a meal,",
      pageIndex: 10,
      icon: "💬",
    },
    {
      id: "reward",
      word: "reward",
      meaning: "something given for good work or behaviour",
      meaningZh: "奖励",
      soundParts: ["re", "ward"],
      example: "And you deserve a reward",
      pageIndex: 15,
      icon: "🏅",
    },
  ],
  "danny-dinosaur-ride-a-bike": [
    {
      id: "bicycle",
      word: "bicycle",
      meaning: "a two-wheeled vehicle moved by pedals",
      meaningZh: "自行车",
      soundParts: ["bi", "cy", "cle"],
      example: "the two friends saw a huge bicycle",
      pageIndex: 2,
      icon: "🚲",
    },
    {
      id: "balancing",
      word: "balancing",
      meaning: "keeping steady without falling",
      meaningZh: "保持平衡",
      soundParts: ["bal", "anc", "ing"],
      example: "Balancing is tricky,",
      pageIndex: 7,
      icon: "⚖️",
    },
    {
      id: "distract",
      word: "distract",
      meaning: "to take someone's attention away",
      meaningZh: "分散注意力",
      soundParts: ["dis", "tract"],
      example: "Here, I'll distract you.",
      pageIndex: 8,
      icon: "🎵",
    },
    {
      id: "pedals",
      word: "pedals",
      meaning: "parts pushed by the feet to move a bicycle",
      meaningZh: "脚踏板（复数）",
      soundParts: ["ped", "als"],
      example: "Danny put his feet on the pedals.",
      pageIndex: 14,
      icon: "🦶",
    },
    {
      id: "practising",
      word: "practising",
      meaning: "doing something repeatedly to improve",
      meaningZh: "正在练习",
      soundParts: ["prac", "tis", "ing"],
      example: "I've been practising,",
      pageIndex: 15,
      icon: "💪",
    },
  ],
};

export function wordsForBook(bookSlug: string): VocabularyWord[] {
  return WORD_SETS[bookSlug] ?? [];
}

export function wordAudioSource(bookSlug: string, wordId: string): string {
  return `/word-audio/${bookSlug}/${wordId}.mp3`;
}
